export const EnvVariables = {
  AWS: {
    REGION: 'AWS_REGION',
    DYNAMODB_ENDPOINT: 'AWS_DYNAMODB_ENDPOINT',
    ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID',
    SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY',
  },

  DYNAMODB: {
    TABLE_MESSAGES: 'DYNAMODB_TABLE_MESSAGES',
    CLIENT: 'DYNAMODB_CLIENT',
    TABLE_NAME: 'messages',
  },
} as const;
